# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YNeWZDXTncKvolCKZ8Y8YFE0zRspgqU4
"""

import pandas as pd
import io
import numpy as np
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import warnings
import pickle

admission_predict_df = pd.read_csv('Admission_Predict.csv')

admission_predict_df.head()

admission_predict_df.shape

dataset = admission_predict_df.drop('Serial No.', axis=1)
dataset.head()

X = dataset.iloc[:, 0:-1].values
Y = dataset.iloc[:, -1].values

X.shape

Y.shape

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=52)

from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(X_train, Y_train)

Y_pred = regressor.predict(X_test)
print(Y_pred)

print(regressor.predict([[300, 115, 5, 4, 5, 9.5, 1]]))

from sklearn.metrics import accuracy_score
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

score = r2_score(Y_test, Y_pred)
print(score)

pickle.dump(regressor, open('model.pkl', 'wb'))
model = pickle.load(open('model.pkl', 'rb'))
